opentracing:
  spring:
    cloud:
      websocket:
        enabled: false

server:
  port: 8085

endpoints:
  enabled: false
  metrics:
    enabled: true
  health:
    enabled: true
    sensitive: true
  info:
    enabled: true

spring:
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      indent_output: true

scheduler:
  redis_host: "localhost"
  redis_port: 6379
  instant_eval_forward: false
  trial_run_forward: false 
  default_queue: "zmon:queue:default"
  last_run_persist: DISABLED
  check_detail_metrics: true
  oauth2_scopes: ["uid"]
  thread_count: 8
  check_filter: []
  disable_persisted_schedule: true
  enable_global_entity: true
  task_writer_type: REDIS
  entity_service_url: http://localhost:8080
  controller_url: http://localhost:8080
  entity_properties_key: "zmon:entity:properties"

